before_install:
  - sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk

script: 
  - ./build.sh

after_success:
  - ./deploy.sh

env:
  global:
    - BUILD_DIR="_build"
    - ENCRYPTION_LABEL="d6a76f5bfedb"
    - GIT_NAME="Paul Bryan"
    - GIT_EMAIL="pabryan@gmail.com"
    - SOURCE_BRANCH="master"
    - TARGET_BRANCH="gh-pages"
